/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.search.yahoo;

import java.net.URL;
import java.net.URLEncoder;
import org.openide.awt.HtmlBrowser.URLDisplayer;

/**
 *
 * @author marcos
 */
public class YahooPainel3 extends javax.swing.JPanel {

    private javax.swing.JLabel      jLabelYahoo;
    private javax.swing.JTextField  jTextFieldYahoo;
    
    /**
     * Creates new form YahooPainel3
     */
    public YahooPainel3() {
        initComponent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(YahooPainel3.class, "YahooPainel3.jLabelYahoo.text")); // NOI18N
        jLabel1.setToolTipText(org.openide.util.NbBundle.getMessage(YahooPainel3.class, "YahooPainel3.jLabel1.toolTipText")); // NOI18N
        jLabel1.setName("jLabelYahoo"); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(YahooPainel3.class, "YahooPainel3.jTextField1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void initComponent(){
        jLabelYahoo     = new javax.swing.JLabel();
        jTextFieldYahoo = new javax.swing.JTextField();
        
        org.openide.awt.Mnemonics.setLocalizedText(jLabelYahoo,org.openide.util.NbBundle.getMessage(YahooPainel3.class, "YahooPainel3.jLabelYahoo.text")); // NOI18N
//        jLabelYahoo.setToolTipText(org.openide.util.NbBundle.getMessage(YahooPainel3.class, "YahooPainel3.jLabelYahoo.toolTipText")); // NOI18N
        jLabelYahoo.setName("jLabelYahoo"); // NOI18N
        jLabelYahoo.setText("Y! Search");
        

//        jTextFieldYahoo.setText(org.openide.util.NbBundle.getMessage(YahooPainel3.class, "YahooPainel3.jTextFieldYahoo.text")); // NOI18N
//        jTextFieldYahoo.setText("Insira o termo de busca....");
        jTextFieldYahoo.addActionListener(new java.awt.event.ActionListener() {
            
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt){
                jTextFieldYahooActionPerformed(evt);
            }
            
            
        });        

        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelYahoo, javax.swing.GroupLayout.PREFERRED_SIZE,64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,16, Short.MAX_VALUE)
                .addComponent(jTextFieldYahoo, javax.swing.GroupLayout.PREFERRED_SIZE,200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldYahoo, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabelYahoo))
                .addContainerGap())
        );        
        
    }

    
    private void jTextFieldYahooActionPerformed(java.awt.event.ActionEvent evt){
    
    try {
        
        String searchText = URLEncoder.encode(jTextFieldYahoo.getText(), "UTF-8");
        URLDisplayer.getDefault().showURL(
                new URL(
                        "http://br.search.yahoo.com/search?p="+searchText)
                );
    } catch (Exception err){
        err.getMessage();
    }
    
}    
    
    
}
